# MINEKING CORE - BEAUTYBLOOD

settings:
   prefix: "§6§lM§e§lK §8>"
   blockWitherSpawn: false
   blockBlazeWaterDamage: false
   unicodeCrash: true
   blockSpawnerEggChange: true
   blockCactusDamage: true
   blockVillagerTrades: true
   # SpawnEvent
   blockMobSpawns: true
   blockSpawnMobs:
   - "MineKingSpecialMobContain"